fileVersion: 1
id: "23"
mappingDefinitions:
  DIM:
    database: ""
    schema: ""
  IM_RPT:
    database: ""
    schema: ""
  SRC:
    database: SAMPLE_DATA
    schema: LOAD
  STAGE:
    database: ""
    schema: ""
name: PROD
type: Environment
