fileVersion: 1
id: "23"
mappingDefinitions:
  DIM:
    database: SAMPLE_DATA
    schema: DIM
  FACT:
    database: SAMPLE_DATA
    schema: FACT
  IM_RPT:
    database: SAMPLE_DATA
    schema: IM_RPT
  SRC:
    database: SAMPLE_DATA
    schema: LOAD
  STAGE:
    database: SAMPLE_DATA
    schema: STAGE
name: PROD
type: Environment
